### ISSUE TITLE
infer_server是否有考虑过集入nvidia-triton-server？

### ISSUE THREAD

**Issue by YuxiangJohn** [Cambricon/easydk#14]
请问是否考虑过将cambricon作为backend集成进nvidia-triton-server。目前paddle-paddle， pytorch， tensorrt作为一种backend集成入了triton。如果从通用度或者生态考虑，是否有机会集成入triton？另外，目前nvidia的做法是Deepstream+triton，其中triton的的地位与infer_server类似，也是可以作为Deepstream的一个module。然而从我使用者的角度看，更希望的是server内部包含Deepstream（infer_server 包含 cnstream），类似于triton中的ensamble模型（emsamble不够灵活），以cnstream增加pipeline构建灵活度，以infer_server解决服务调度等问题，最终以infer_server作为出口，支持rpc/http调用。

**Comment by MaxwellDing** [comment]
没有集成nvidia-triton-server的规划。
目前infer_server仅支持C++ API调用，还没有加入HTTP/gRPC之类的接口。我们也在探究未来的开发方向，但是包含CNStream不在infer_server的规划范畴内，这应该是由其他模块负责的。
目前CNStream有一套简单的web server，在CNStream/tools/web_visualize，但是功能还不够完善，仅供参考
非常感谢您的关注和建议！
