### ISSUE TITLE
Question about "samples/classification_runner.hpp"

### ISSUE THREAD

**Issue by chaffeechenyefei** [Cambricon/easydk#16]
In "samples/classification_runner.hpp",  the variable ```model_``` is used to initial class ```edk::EasyInfer infer_```. After that, ```model_``` is  used to get the input shape. But in "src/easyinfer/easy_infer.cpp", the ```EasyInfer::Init()``` function treat the input parameter ```std::shared_ptr<ModelLoader> model``` with ```std::move``` like ```d_ptr_->model_ = std::move(model)```. Perhaps, it might cause error in debugging "samples/classification_runner.hpp", because ```model_``` is an empty pointer.

Codes from "samples/classification_runner.hpp":
```
ClassificationRunner::ClassificationRunner(const std::string& model_path, const std::string& func_name,
                                           const std::string& label_path, const std::string& data_path, bool show,
                                           bool save_video)
    : StreamRunner(data_path), show_(show), save_video_(save_video) {
  // load offline model
  model_ = std::make_shared<edk::ModelLoader>(model_path.c_str(), func_name.c_str());

  // prepare mlu memory operator and memory
  mem_op_.SetModel(model_);

  // init easy_infer
  infer_.Init(model_, 0);

  // create mlu resize and convert operator
  auto& in_shape = model_->InputShape(0);
```

**Comment by MaxwellDing** [comment]
model is passed to EasyInfer by value, it is a copy of shared pointer in EasyInfer, so that the move process won't affect pointer outside.
Thank you for your attention.
